ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v1.0.0-rc.22
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: widget-b
        workflow: .github/workflows/build-widget.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
  state:
    prerelease:
      sha: 78ba097497d2ee33f520da06f78bcd7a43e6ad79
      version: v0.1.0-rc.6
      committed_at: "2026-06-17T19:01:06Z"
      committed_by: joshua-temple
