ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v1.0.0-rc.12
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: widget-b
        workflow: .github/workflows/build-widget.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
  state: {}
