ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.14.1-dryrun.58
    cli_version_sha: 33f8865a69ee8c318876539582e15e4ccee3949e
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: widget-b
        workflow: .github/workflows/build-widget.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
      deploy_name: artifact-b
      environment: staging
  state:
    prerelease:
      sha: 9ec48d37016c03938b30f37383dac4ec013d9793
      version: v0.1.0-rc.0
      committed_at: "2026-07-11T09:20:45Z"
      committed_by: joshua-temple
